### ISSUE TITLE
How to drop RPGInv items from MythicMobs

### ISSUE THREAD

**Issue by trungbmt** [OsipXD/RPGInventory#131]
I created items required level with items files in RPGInventory, but I can not make items required level with mythicmobs plugin, because I want the monsters I created to drop items required level.
Lore the same level requirements but rpginventory's items worked and mythicmobs did not work

Sorry, my bad english

### Environment

**Server Core:** Spigot
**Server Version:** 1.12.2
**Plugin Version:** 2.1.5-PRE

**Comment by OsipXD** [comment]
Mythic mobs item level restriction not works with RPGInv slots, sure?

**Comment by trungbmt** [comment]
I want the rpginventory items to be dropped through the mobs of mythicmobs so I created an item in rpginventory items file:
```
assassin-gloves:
    texture: DIAMOND_HOE:24
    name: "Assassin gloves"
    lore:
    - "&e&oFaster than the wind..."
    rarity: RARE
    unbreakable: true
    level: 4
```


And then I tried to do the same thing with mythicmobs so that both were the same but it did not work  
Mythicmobs items:

```
AssasinGloves:
  Id: 276
  Data: 0
  Display: '&9Assassin gloves'
  Lore:
  - '&rRequires 4 level'
  - ''
  - '&e&oFaster than the wind...'
  Options:
    Unbreakable: true
  Hide:
  - ATTRIBUTES
  - UNBREAKABLE
```

Item created from rpginventory it requires level to use, while mythicmobs it does not require ...
